### ISSUE TITLE
Why do you need to have ~erasure() pure virtual?

### ISSUE THREAD

**Issue by MartinMoizard** [PaulHowes/any#1]
Hi Paul,

This is more a question that an issue.

I am wondering why you declared `~erasure()` as pure virtual and defined it later with `any::erasure::~erasure() { }` ?

I would simply do `virtual ~erasure() { }` or `virtual ~erasure() = default;`. Is there a difference?

Thanks a lot

**Comment by pahowes** [comment]
Since I'm using `erasure` as an interface (pure virtual class) to access `erasure_impl` instances, a destructor is required. For example:

``` c++
struct A {
  virtual void f() = 0;
};

struct B : A {
  virtual void f() { };
};

int main() {
  A* a = new B;
  delete a;
  return 0;
}
```

Compiling this will result in the following warning:

```
warning: delete called on 'A' that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
```

Now let's add a destructor, with an implementation, to A:

``` C++
struct A {
  ~A() { }
  virtual void f() = 0;
};
```

The same warning will occur since the destructor is not virtual. Now let's change it to be virtual:

``` C++
struct A {
  virtual ~A() { }
  virtual void f() = 0;
};
```

Now you'll receive a warning like this:

```
warning: 'A' has no out-of-line virtual method definitions; its vtable will be emitted in every translation unit [-Wweak-vtables]
```

All right, let's make the destructor pure virtual as well, then implement it in the sub-class:

``` c++
struct A {
  virtual ~A() = 0;
  virtual void f() = 0;
};

struct B : A {
  virtual void f() { }
  virtual ~B() { }
};
```

The compiler will now issue an error instead of a warning!

```
Undefined symbols for architecture x86_64:
  "A::~A()", referenced from:
      B::~B() in one-71d932.o
ld: symbol(s) not found for architecture x86_64
```

If we split the classes so that the header contains only the interface and a source file (.cpp, .cc, etc.) contains the implementation, this problem goes away. However that defeats the purpose of distributing a header-only library.

One last try: Let's make the destructor pure virtual in `A`, omit it from `B`, then define the body outside of `A`:

``` c++
struct A {
  virtual ~A() = 0;
  virtual void f() = 0;
};

struct B : A {
  virtual void f() { }
};

inline A::~A() { }
```

Now the code compiles with no warnings and no errors!

Since the derived class, `B` will call the parent class's destructor, it needs to be implemented somewhere. Here's posting from Herb Sutter that explains it as well (question 2, answer 1): http://www.gotw.ca/gotw/031.htm

**Comment by MartinMoizard** [comment]
Thanks a lot for your answer, it's helping a lot.

I am having an issue (duplicated symbols of type::any::erasure) when I build my project with your header. I fixed it by replacing `any::erasure::~erasure() {}` by `inline any::erasure::~erasure() {}`.

Do you see any reason why I could not inline any::erasure::~erasure() {}?

Thanks again

**Comment by pahowes** [comment]
That was my mistake. It should have been inline (per my example above). Fixed and pushed. Thanks for letting me know!

**Comment by MartinMoizard** [comment]
Ok thanks :)
